version: "3.9"
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  backend:
    build: ./backend
    environment:
      - MONGODB_URI=mongodb://mongo:27017/airline-blockchain
      - PORT=3001
    depends_on:
      - mongo
    ports:
      - "3001:3001"
volumes:
  mongo_data: