name: Backend CI

on:
  push:
    paths:
      - "airline-blockchain/backend/**"
      - ".github/workflows/backend.yml"
  pull_request:
    paths:
      - "airline-blockchain/backend/**"

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
    defaults:
      run:
        working-directory: airline-blockchain/backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: airline-blockchain/backend/package.json
      - run: npm install
      - run: npm test
        env:
          MONGODB_URI: mongodb://localhost:27017/airline-blockchain-test